name : Node.js CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2 

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: yarn install
      working-directory: client

    - run: yarn build
      working-directory: client